# SPDX-FileCopyrightText: no
# SPDX-License-Identifier: CC0-1.0

# https://github.com/calamares/calamares/blob/calamares/src/modules/packagechooser/packagechooser.conf
---
items:
  - id: refind
    name: "KDE Plasma"
    description: "KDE Plasma is a graphical workspaces environment created by KDE primarily for Linux systems. The graphical interface was fully migrated to QML, which uses OpenGL for hardware acceleration, which resulted in better performance and reduced power consumption."
    screenshot: "/etc/calamares/images/desktops/plasma.png"
    netinstall:
      name: KDE Plasma Desktop
      description: Options for the KDE Plasma desktop installation
      noncheckable: true
      ignore-share-state: true
      subgroups:
        - name: Curated
          description: Hand-picked offering of the KDE Plasma desktop
          selected: true
          critical: true
          packages:
            - name: sddm
              description: Display manager and login screen
            - name: sddm-kcm
              description: KDE Config Module for SDDM

mode: requiredmultiple
method: netinstall-add
labels:
  step: "Bootloader"
qmlFilename: packagechooserq_bootloader.qml
promptmessage: "Please select the bootloader to install."
default: budgie
outputconditionkey: "desktops_chosen"
